services:
  # Backend
  - type: web
    name: insightra-backend
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker server.main:app --bind 0.0.0.0:$PORT --timeout 120
    plan: free
    branch: main
    repo: https://github.com/saidurgaphani/CS2026
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DATABASE_NAME
        value: CS2026
      - key: GEMINI_API_KEY
        sync: false
